# This config file will create a cluster on AWS
cluster_manager: mf-manager
backend_provider: local
name: mf-cluster
cluster_cloud_provider: aws
k8s_version: v1.13.4-rancher1-1
k8s_network_provider: calico
private_registry: ""
private_registry_username: ""
private_registry_password: ""
k8s_registry: ""
k8s_registry_username: ""
k8s_registry_password: ""
aws_access_key: AKIASEG5YA6MM7RRLVNL
aws_secret_key: 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
aws_region: us-east-2
aws_vpc_cidr: 172.18.0.0/16
aws_subnet_cidr: 172.18.1.0/24
aws_public_key_path: ~/.ssh/ilm_aws_rsa.pub
aws_private_key_path: ~/.ssh/ilm_aws_rsa
aws_key_name: triton-kubernetes_public_key_02
ebs_volume_device_name: "/dev/sdf"
ebs_volume_mount_path: "/mnt/triton-kubernetes"
ebs_volume_type: gp2
nodes:
  - node_count: 1
    rancher_host_label: etcd
    hostname: mf-cl-etcd
    aws_ami_id: ami-0510c89f1a2691cf2
    aws_instance_type: t2.small
    ebs_volume_iops: 100
    ebs_volume_size: 10
  - node_count: 1
    rancher_host_label: control
    hostname: mf-cl-control
    aws_ami_id: ami-0510c89f1a2691cf2
    aws_instance_type: t2.small
    ebs_volume_iops: 100
    ebs_volume_size: 10
  - node_count: 1
    rancher_host_label: worker
    hostname: mf-cl-worker
    aws_ami_id: ami-0510c89f1a2691cf2
    aws_instance_type: t2.small
    ebs_volume_iops: 100
    ebs_volume_size: 10


