# This config file will create a Cluster Manager which will be running on Google Cloud Platform
backend_provider: local
name: mf-gcp-man01
manager_cloud_provider: gcp
private_registry: ""
private_registry_username: ""
private_registry_password: ""
rancher_server_image: ""
rancher_agent_image: ""
gcp_path_to_credentials: ~/.ssh/gcp-tk8s.json
gcp_compute_region: us-east1
gcp_instance_zone: us-east1-b
gcp_machine_type: g1-small
gcp_image: ubuntu-1604-xenial-v20190430
gcp_public_key_path: ~/.ssh/ilm_gcp_rsa.pub
gcp_private_key_path: ~/.ssh/ilm_gcp_rsa
gcp_ssh_user: root
rancher_admin_password: Dfrfyne.