cluster_manager: {{MANAGER_NAME}}
backend_provider: local
cluster_name: {{CLUSTER_NAME}}
cluster_cloud_provider: aws
k8s_version: v1.13.4-rancher1-1
k8s_network_provider: calico
private_registry: ""
private_registry_username: ""
private_registry_password: ""
k8s_registry: ""
k8s_registry_username: ""
k8s_registry_password: ""
aws_access_key: {{AWS_ACCESS_KEY}}
aws_secret_key: {{AWS_SECRET_KEY}}
aws_region: eu-west-2
aws_vpc_cidr: 172.18.0.0/16
aws_subnet_cidr: 172.18.1.0/24
aws_public_key_path: {{AWS_PUBLIC_KEY_PATH}}
aws_private_key_path: {{AWS_PRIVATE_KEY_PATH}}
aws_key_name: triton-kubernetes_public_key_02
ebs_volume_device_name: "/dev/sdf"
ebs_volume_mount_path: "/mnt/triton-kubernetes"
ebs_volume_type: "gp2"
node_count: {{WORKER_NODE_COUNT}}
rancher_host_label: worker
hostname: {{WORKER_NODE_NAME}}
aws_ami_id: ami-0510c89f1a2691cf2
aws_instance_type: t2.small
ebs_volume_iops: 100
ebs_volume_size: 10
