# This config file will create a node on AWS
cluster_manager: {{MCP_MANAGER_NAME}}
backend_provider: local
cluster_name: {{MCP_CLUSTER_NAME}}
cluster_cloud_provider: aws
k8s_version: v1.13.4-rancher1-1
k8s_network_provider: {{MCP_K8S_NETWORK_PROVIDER}}
private_registry: ""
private_registry_username: ""
private_registry_password: ""
k8s_registry: ""
k8s_registry_username: ""
k8s_registry_password: ""
# set AWS access and secret keys
aws_access_key: {{MCP_AWS_ACCESS_KEY}}
aws_secret_key: {{MCP_AWS_SECRET_KEY}}
aws_region: eu-west-2
aws_vpc_cidr: 172.22.0.0/16
aws_subnet_cidr: 172.22.1.0/24
aws_public_key_path: {{MCP_AWS_PUBLIC_KEY_PATH}}
aws_private_key_path: {{MCP_AWS_PRIVATE_KEY_PATH}}
aws_key_name: {{MCP_AWS_CLUSTER_KEY_NAME}}
ebs_volume_device_name: "/dev/sdf"
ebs_volume_mount_path: "/mnt/triton-kubernetes"
ebs_volume_type: gp2
# chose the OS distributive and specify 'aws_ami_id' for each node
node_count: {{MCP_NODE_COUNT}}
rancher_host_label: {{MCP_NODE_TYPE}}
hostname: {{MCP_NODE_NAME}}
aws_ami_id: ami-04606ba5d5fb731cc
aws_instance_type: t2.small
ebs_volume_iops: 100
ebs_volume_size: 10
