# This config file will create an HA cluster on Joyent Cloud (Triton) attached to triton-ha Cluster Manager
cluster_manager: {{MANAGER_NAME}}
backend_provider: local
name: {{CLUSTER_NAME}}
cluster_cloud_provider: gcp
k8s_version: v1.13.4-rancher1-1
k8s_network_provider: calico
private_registry: ""
private_registry_username: ""
private_registry_password: ""
k8s_registry: ""
k8s_registry_username: ""
k8s_registry_password: ""
gcp_path_to_credentials: {{GCP_PATH_TO_CREDENTIALS}}
gcp_compute_region: us-east1
nodes:
  - node_count: {{ETCD_NODE_COUNT}}
    rancher_host_label: etcd
    hostname: {{ETCD_NODE_NAME}}
    gcp_instance_zone: us-east1-b
    gcp_machine_type: g1-small
    gcp_image: ubuntu-1604-xenial-v20190430
    gcp_public_key_path: {{GCP_PUBLIC_KEY_PATH}}
    gcp_private_key_path: {{GCP_PRIVATE_KEY_PATH}}
    gcp_ssh_user: root
  - node_count: {{CONTROL_NODE_COUNT}}
    rancher_host_label: control
    hostname: {{CONTROL_NODE_NAME}}
    gcp_instance_zone: us-east1-b
    gcp_machine_type: g1-small
    gcp_image: ubuntu-1604-xenial-v20190430
    gcp_public_key_path: {{GCP_PUBLIC_KEY_PATH}}
    gcp_private_key_path: {{GCP_PRIVATE_KEY_PATH}}
    gcp_ssh_user: root
  - node_count: {{WORKER_NODE_COUNT}}
    rancher_host_label: worker
    hostname: {{WORKER_NODE_NAME}}
    gcp_instance_zone: us-east1-b
    gcp_machine_type: g1-small
    gcp_image: ubuntu-1604-xenial-v20190430
    gcp_public_key_path: {{GCP_PUBLIC_KEY_PATH}}
    gcp_private_key_path: {{GCP_PRIVATE_KEY_PATH}}
    gcp_ssh_user: root
