# This config file will create a cluster on GCP
cluster_manager: {{MCP_MANAGER_NAME}}
backend_provider: local
name: {{MCP_CLUSTER_NAME}}
cluster_cloud_provider: gcp
k8s_version: v1.13.4-rancher1-1
k8s_network_provider: {{MCP_K8S_NETWORK_PROVIDER}}
private_registry: ""
private_registry_username: ""
private_registry_password: ""
k8s_registry: ""
k8s_registry_username: ""
k8s_registry_password: ""
gcp_path_to_credentials: {{MCP_GCP_CREDENTIALS_PATH}}
gcp_compute_region: {{MCP_GCP_DEFAULT_REGION}}
nodes:
  - node_count: {{MCP_ETCD_NODE_COUNT}}
    rancher_host_label: etcd
    hostname: {{MCP_ETCD_NODE_NAME}}
    gcp_instance_zone: {{MCP_GCP_DEFAULT_REGION}}-b
    gcp_machine_type: g1-small
    gcp_image: ubuntu-1604-xenial-v20190430
    gcp_public_key_path: {{MCP_GCP_PUBLIC_KEY_PATH}}
    gcp_private_key_path: {{MCP_GCP_PRIVATE_KEY_PATH}}
    gcp_ssh_user: root
  - node_count: {{MCP_CONTROL_NODE_COUNT}}
    rancher_host_label: control
    hostname: {{MCP_CONTROL_NODE_NAME}}
    gcp_instance_zone: {{MCP_GCP_DEFAULT_REGION}}-b
    gcp_machine_type: g1-small
    gcp_image: ubuntu-1604-xenial-v20190430
    gcp_public_key_path: {{MCP_GCP_PUBLIC_KEY_PATH}}
    gcp_private_key_path: {{MCP_GCP_PRIVATE_KEY_PATH}}
    gcp_ssh_user: root
  - node_count: {{MCP_WORKER_NODE_COUNT}}
    rancher_host_label: worker
    hostname: {{MCP_WORKER_NODE_NAME}}
    gcp_instance_zone: {{MCP_GCP_DEFAULT_REGION}}-b
    gcp_machine_type: g1-small
    gcp_image: ubuntu-1604-xenial-v20190430
    gcp_public_key_path: {{MCP_GCP_PUBLIC_KEY_PATH}}
    gcp_private_key_path: {{MCP_GCP_PRIVATE_KEY_PATH}}
    gcp_ssh_user: root
