# This config file will create a Cluster Manager which will be running on Google Cloud Platform
backend_provider: local
name: {{MCP_MANAGER_NAME}}
manager_cloud_provider: gcp
private_registry: ""
private_registry_username: ""
private_registry_password: ""
rancher_server_image: ""
rancher_agent_image: ""
gcp_credentials_path: {{MCP_GCP_CREDENTIALS_PATH}}
gcp_compute_region: {{MCP_GCP_DEFAULT_REGION}}
gcp_instance_zone: {{MCP_GCP_DEFAULT_REGION}}-b
gcp_machine_type: g1-small
gcp_image: ubuntu-1604-xenial-v20190430
gcp_public_key_path: {{MCP_GCP_PUBLIC_KEY_PATH}}
gcp_private_key_path: {{MCP_GCP_PRIVATE_KEY_PATH}}
gcp_ssh_user: root
rancher_admin_password: {{MCP_RANCHER_ADMIN_PWD}}
